// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbkrNnSQdpXAKFU4cZZbEQRa27UIHcYzc',
    appId: '1:893716088706:web:164a46d18c59e61183b19b',
    messagingSenderId: '893716088706',
    projectId: 'pricedivider',
    authDomain: 'pricedivider.firebaseapp.com',
    storageBucket: 'pricedivider.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR4b0htHsSnRfzpO-tVIO2KQnzxe99uKU',
    appId: '1:893716088706:android:110b2e9ad3806d4c83b19b',
    messagingSenderId: '893716088706',
    projectId: 'pricedivider',
    storageBucket: 'pricedivider.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxK5uBi3ludsywG6dSEJ9L_2K1XL_An1s',
    appId: '1:893716088706:ios:bcd0867521b4d52483b19b',
    messagingSenderId: '893716088706',
    projectId: 'pricedivider',
    storageBucket: 'pricedivider.appspot.com',
    iosClientId: '893716088706-st54u5rptgpqsapn3b7nln2d1jekgqih.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxK5uBi3ludsywG6dSEJ9L_2K1XL_An1s',
    appId: '1:893716088706:ios:bcd0867521b4d52483b19b',
    messagingSenderId: '893716088706',
    projectId: 'pricedivider',
    storageBucket: 'pricedivider.appspot.com',
    iosClientId: '893716088706-st54u5rptgpqsapn3b7nln2d1jekgqih.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
